version: "3.8"

services:
  api_rest:
    container_name: workshop
    image: ochamodev/workshop_server:1.0.13
    restart: on-failure
    ports:
      - "3000:8080"
    networks:
      - mysql_net
    depends_on:
      - workshopDB

  workshopDB:
    container_name: mysqlDBTest
    image: mysql:8.0
    restart: on-failure
    networks:
      - mysql_net
    environment:
      - MYSQL_ROOT_PASSWORD=Snw9Dv75j0rF9F2FwTPNw0clt
      - MYSQL_ROOT_USER=root
    ports:
      - "3307:3306"
    volumes:
      - "/home/scripts:/docker-entrypoint-initdb.d"
      - "/home/apps/workshop_db_dir:/var/lib/mysql"


networks:
  mysql_net:
    driver: bridge

